### ISSUE TITLE
When "Keyboard" is selected as the "Icon" type for an ActionPrompt node, or if it's left on Automatic, keyboard_textures.gd seems to fail to look up the correct string in the dictionary for the keyboard glyph.

### ISSUE THREAD

**Issue by Zero-Sennin** [Pennycook/godot-input-prompts#4]
Occurs in Godot 4.1.2.stable.mono (using C# for all other scripts).

I have assigned joystick, keyboard, and d-pad inputs to the input in question in my project settings:
![image](https://github.com/Pennycook/godot-input-prompts/assets/6941339/f39db6c5-8dd0-4ade-bee3-757f04e932d7)

And when the "Icon" type is set to "Keyboard":
![image](https://github.com/Pennycook/godot-input-prompts/assets/6941339/37f7f217-909b-4764-9384-e539b59a5253)

I get this error message; 
res://addons/input_prompts/resources/keyboard_textures.gd:27 - Invalid get index of type 'String' (on base: 'Dictionary').

This also happens when "Automatic" is enabled, but switching to Xbox, Playstation, or Nintendo sidesteps the issue entirely.

**Comment by Pennycook** [comment]
Thanks for the report!  I suspect this might have been fixed by #2, which isn't available in the asset library yet.

Could you please try installing the plugin from here (or just make the same changes from https://github.com/Pennycook/godot-input-prompts/commit/b7bc3777ba4ca6c41e0773ee3b64827346046fcd in your local copy) and let me know if that fixes the issue?  If it does, I'll push a new release to the asset library.

**Comment by Zero-Sennin** [comment]
I just applied the change and it works perfectly! Thank you very much.
