### ISSUE TITLE
Texture Filter is not set to nearest by default

### ISSUE THREAD

**Issue by betalars** [Pennycook/godot-input-prompts#5]
Your Icons right now look incredibly blurry when used in game, because the texture filter in ActionPrompt for instance is not set to "Nearest".

I would add an option that is disabled by default and can be overwritten by the user, if they use a high rez texture pack.

**Comment by Pennycook** [comment]
Sorry, but could you provide a little more information about where you see the issue?

If I install the add-on in a fresh Godot project, the texture filter in `ActionPrompt` is set to "Inherit".

**Comment by betalars** [comment]
Oh Sorry, I forgot to answer:

I have thought about it and it is probably the "correct" thing to do, even tho it causes the icons to appear blurry in most situations: The only proper fix for this would be to include a high rez icon set with the addon, but then again I have trouble figuring out how one would select the high rez or the low rez version.

Alternatively, one could use a high rez pack by default, with would always look kind of good, instead of a low rez pack, that only looks good in the context of games with pixelart aesthetic, but this is another issue.

**Comment by Pennycook** [comment]
> Oh Sorry, I forgot to answer:
> 
> I have thought about it and it is probably the "correct" thing to do, even tho it causes the icons to appear blurry in most situations: The only proper fix for this would be to include a high rez icon set with the addon, but then again I have trouble figuring out how one would select the high rez or the low rez version.
> 
> Alternatively, one could use a high rez pack by default, with would always look kind of good, instead of a low rez pack, that only looks good in the context of games with pixelart aesthetic, but this is another issue.

Thanks for getting back to me about this.

I see where you're coming from.  I initially developed this plugin for myself, and I didn't see the issue because I primarily work on pixel art games.

I've recently learned how to add configuration options to the ProjectSettings, so I'll look into adding a few different icon styles into the add-on.  Since Godot requires editing the ProjectSettings for pixel art games anyway, defaulting to high-resolution icons probably makes sense.
