### ISSUE TITLE
Acton Prompt raises Editor Errors when used

### ISSUE THREAD

**Issue by betalars** [Pennycook/godot-input-prompts#6]
When I add an Action Prompt to the Editor, I get tons of Error Messages like these:
`core/variant/variant_utility.cpp:1091 - No Joypad input for ui_cancel in InputMap`

These obviousely go away when I switch to keyboard mode and are caused by godot not having Joypad Buttons assigned for each Built In Input. But when adding your AddOn to any fresh project, it just causes tons of errors and I will have a look and see if I can resolve this.

**Comment by betalars** [comment]
Okay somehow it is caused by _update_icon() being called whenever you do a UI Input, but I have not understood what keeps calling this function in editor. For now I think the easiest fix is just to set the editor default to KEYBOARD on `input_prompt_manager.gd` Line 23.

That way this error message spam is not resolved, but at least it will only show up all the time when add a new InputPrompt and have it set to UI_accept.

**Comment by Pennycook** [comment]
Thank you for the report.

I don't think it makes sense to suppress these errors completely, because then it would be very hard for a user to identify why the plug-in wasn't working for certain actions.  But I agree that printing an error on every input is a bad solution.  I've got an idea for a different fix, which should still highlight configuration issues without all the spam.
